In [3]:
import mne
import numpy as np

# Load the .set file using mne
eeg_data = mne.io.read_raw_eeglab('preprocessed_data/s01_051017m.set/s01_051017m.set', preload=True)

# Display some basic information about the dataset
eeg_data.info

# Extract events from the raw data
events, event_id = mne.events_from_annotations(eeg_data)

# Show the unique event types and their IDs
events

Reading /Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/preprocessed_data/s01_051017m.set/s01_051017m.fdt
Reading 0 ... 1811359  =      0.000 ...  3622.718 secs...
Used Annotations descriptions: ['251', '252', '253', '254']


array([[   6772,       0,       2],
       [   7182,       0,       3],
       [   8570,       0,       4],
       ...,
       [1804250,       0,       1],
       [1804594,       0,       3],
       [1805312,       0,       4]])

In [4]:
deviation_onset_indices = np.where((events[:, 2] == event_id['251']) | (events[:, 2] == event_id['252']))[0]

In [5]:
deviation_onset_indices

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231,
       234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270,
       273, 276, 279, 282, 285, 288, 291, 294, 297, 300, 303, 306, 309,
       312, 315, 318, 321, 324, 327, 330, 333, 336, 339, 342, 345, 348,
       351, 354, 357, 360, 363, 366, 369, 372, 375, 378, 381, 384, 387,
       390, 393, 396, 399, 402, 405, 408, 411, 414, 417, 420, 423, 426,
       429, 432, 435, 438, 441, 444, 447, 450, 453, 456, 459, 462, 465,
       468, 471, 474, 477, 480, 483, 486, 489, 492, 495, 498, 501, 504,
       507, 510, 513, 516, 519, 522, 525, 528, 531, 534, 537, 54

<class 'numpy.ndarray'>


In [19]:
events

array([[   6772,       0,       2],
       [   7182,       0,       3],
       [   8570,       0,       4],
       ...,
       [1804250,       0,       1],
       [1804594,       0,       3],
       [1805312,       0,       4]])

In [9]:
event_id['252']

2

In [12]:
events[deviation_onset_indices, 0]

array([   6772,   11078,   16996,   22128,   26164,   31196,   38260,
         42572,   46050,   53656,   59422,   65046,   69786,   76448,
         81428,   87254,   95956,  101824,  109828,  118076,  122858,
        128584,  139234,  144860,  156552,  163490,  183266,  188524,
        192210,  196514,  200428,  205176,  212698,  215892,  228892,
        233738,  238546,  253832,  260760,  264230,  268968,  283580,
        312374,  321108,  329534,  341578,  344870,  347194,  352302,
        356306,  620850,  624920,  652452,  657510,  686212,  690366,
        696076,  699746,  704308,  709516,  717224,  723852,  729460,
        734850,  740170,  748010,  754062,  758826,  942600,  947564,
        953590,  958356,  965008,  969222,  972666,  976234,  979712,
        985454,  988420,  992408,  995876,  998350, 1003390, 1006166,
       1013654, 1018912, 1023828, 1028258, 1031634, 1038562, 1042232,
       1046938, 1053750, 1057620, 1063278, 1066856, 1070292, 1077054,
       1081100, 1086

In [14]:
np.diff(events[deviation_onset_indices, 0])

array([  4306,   5918,   5132,   4036,   5032,   7064,   4312,   3478,
         7606,   5766,   5624,   4740,   6662,   4980,   5826,   8702,
         5868,   8004,   8248,   4782,   5726,  10650,   5626,  11692,
         6938,  19776,   5258,   3686,   4304,   3914,   4748,   7522,
         3194,  13000,   4846,   4808,  15286,   6928,   3470,   4738,
        14612,  28794,   8734,   8426,  12044,   3292,   2324,   5108,
         4004, 264544,   4070,  27532,   5058,  28702,   4154,   5710,
         3670,   4562,   5208,   7708,   6628,   5608,   5390,   5320,
         7840,   6052,   4764, 183774,   4964,   6026,   4766,   6652,
         4214,   3444,   3568,   3478,   5742,   2966,   3988,   3468,
         2474,   5040,   2776,   7488,   5258,   4916,   4430,   3376,
         6928,   3670,   4706,   6812,   3870,   5658,   3578,   3436,
         6762,   4046,   5824,   4690,   3770,   5608,   3594,   5242,
         3092,  11050,   3276,   4948,   5216,   6236,   5164,  12162,
      

In [32]:
events

array([[   6772,       0,       2],
       [   7182,       0,       3],
       [   8570,       0,       4],
       ...,
       [1804250,       0,       1],
       [1804594,       0,       3],
       [1805312,       0,       4]])

In [34]:
 event_id

{'251': 1, '252': 2, '253': 3, '254': 4}

In [18]:
 events[6 , 0]

16996

In [28]:
 events, event_id = mne.events_from_annotations(eeg_data)

            # Get indices of deviation onset events
deviation_onset_indices = np.where((events[:, 2] == event_id['251']) | (events[:, 2] == event_id['252']))[0]

            # Filter out events that occur less than 9 seconds apart
filtered_indices = deviation_onset_indices[
np.where(np.diff(events[deviation_onset_indices, 0]) < 9 * eeg_data.info['sfreq'])[0]]

            # Calculate local RT for each trial: time from deviation onset to response onset
local_rt = events[filtered_indices + 1, 0] - events[filtered_indices, 0]

Used Annotations descriptions: ['251', '252', '253', '254']


In [40]:
filtered_indices

array([  0,   9,  18,  21,  81,  84,  87,  96, 114, 135, 138, 144, 150,
       162, 168, 216, 219, 222, 225, 231, 234, 237, 240, 246, 258, 261,
       267, 276, 282, 285, 291, 300, 306, 312, 318, 342, 363, 366, 372,
       375, 381, 384, 387, 390, 393, 399, 405, 408, 411, 423, 438, 441,
       447, 453, 462, 465, 477, 483, 486, 492, 498, 510, 513, 522, 525,
       534, 540, 543, 546, 549, 552, 558, 564, 585, 588, 591])

In [35]:
deviation_onset_indices

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231,
       234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270,
       273, 276, 279, 282, 285, 288, 291, 294, 297, 300, 303, 306, 309,
       312, 315, 318, 321, 324, 327, 330, 333, 336, 339, 342, 345, 348,
       351, 354, 357, 360, 363, 366, 369, 372, 375, 378, 381, 384, 387,
       390, 393, 396, 399, 402, 405, 408, 411, 414, 417, 420, 423, 426,
       429, 432, 435, 438, 441, 444, 447, 450, 453, 456, 459, 462, 465,
       468, 471, 474, 477, 480, 483, 486, 489, 492, 495, 498, 501, 504,
       507, 510, 513, 516, 519, 522, 525, 528, 531, 534, 537, 54

In [30]:
alert_rt = np.percentile(local_rt, 5)

In [31]:
alert_rt

8.0

In [36]:
filtered_indices

array([  0,   9,  18,  21,  81,  84,  87,  96, 114, 135, 138, 144, 150,
       162, 168, 216, 219, 222, 225, 231, 234, 237, 240, 246, 258, 261,
       267, 276, 282, 285, 291, 300, 306, 312, 318, 342, 363, 366, 372,
       375, 381, 384, 387, 390, 393, 399, 405, 408, 411, 423, 438, 441,
       447, 453, 462, 465, 477, 483, 486, 492, 498, 510, 513, 522, 525,
       534, 540, 543, 546, 549, 552, 558, 564, 585, 588, 591])

In [37]:
events[0 + 1, 0]

7182

In [38]:
events[0 , 0]

6772

In [39]:
local_rt

array([410, 392, 358, 392,  24, 334, 434,  10, 452, 142,  10,   8, 484,
         8,   8, 360,   8, 124, 526,   8, 552,   8,   8,   8, 652, 458,
       410, 476, 418, 436,   8, 494, 410,   8, 192,  10, 534,   8, 334,
       468,   8, 292,   8, 568, 410, 360, 394, 460,   8, 610,   8, 352,
         8,   8, 484, 394, 376, 418, 500, 384, 350, 400, 334, 450, 442,
       334,   8, 384,   8, 318, 302, 310, 342, 350, 502, 392])

['sequences', 'labels']

In [1]:
import numpy as np

# Load the dataset
data = np.load('labeled_data/s01_051017m.npz')
# Check the shape of the sequences and labels
sequences_shape = data['sequences'].shape
labels_shape = data['labels'].shape

# Check the unique values in the labels
unique_labels = np.unique(data['labels'])

sequences_shape, labels_shape, unique_labels


KeyError: 'sequences is not a file in the archive'

In [1]:
import os
import glob
import numpy as np
import matplotlib.pyplot as plt

# Set the path to the folder where the processed data is saved
output_folder = '/Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/Main_TF/labeled_datasets_811'

# Initialize a list to hold the labels of all epochs
all_labels = []

# Get a list of all .npz files in the output folder
filepaths = glob.glob(os.path.join(output_folder, '*.npz'))

# Iterate over the files
for filepath in filepaths:
    # Load the labels from the file
    data = np.load(filepath)
    labels = data['labels']

    # Append the labels to the list
    all_labels.extend(labels)

    # Print the distribution of labels in the current file
    print(f"File: {os.path.basename(filepath)}")
    unique, counts = np.unique(labels, return_counts=True)
    print(dict(zip(unique, counts)))

# Convert the list of all labels to a numpy array
all_labels = np.array(all_labels)

# Print the overall distribution of labels
print("Overall distribution:")
unique, counts = np.unique(all_labels, return_counts=True)
print(dict(zip(unique, counts)))


KeyError: 'labels is not a file in the archive'

In [1]:
import torch
import math

print(torch.backends.mps.is_available())
# True
print(torch.backends.mps.is_built())
# True


True
True


In [1]:
import numpy as np

# Load the .npy file
loaded_features = np.load('/Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/Main_TF/labeled_data/extracted_features/s01_051017m_features.npy')

# Display the shape and some basic information about the loaded features
print("Shape:", loaded_features.shape)
print("Data Type:", loaded_features.dtype)
print("Min Value:", np.min(loaded_features))
print("Max Value:", np.max(loaded_features))
print("Mean Value:", np.mean(loaded_features))


Shape: (120, 870)
Data Type: float64
Min Value: -36.40659439644525
Max Value: 1627.7369057339358
Mean Value: 2.184693942353204


In [3]:
import mne
# Load the EEG data
eeg_data = mne.io.read_raw_eeglab('preprocessed_data/s54_081226m.set/s54_081226m.set', preload=True)
eeg_data

Reading /Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/preprocessed_data/s54_081226m.set/s54_081226m.fdt
Reading 0 ... 1230519  =      0.000 ...  2461.038 secs...


<RawEEGLAB | s54_081226m.fdt, 30 x 1230520 (2461.0 s), ~281.7 MB, data loaded>

In [4]:
events, event_id = mne.events_from_annotations(eeg_data)

Used Annotations descriptions: ['251', '252', '253', '254', '255']


Deleted: /Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/preprocessed_data/s09_060317n.set/s09_060317n.set_labeled_data.pkl
Deleted: /Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/preprocessed_data/s41_091104n.set/s41_091104n.set_labeled_data.pkl
Deleted: /Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/preprocessed_data/s35_070115m.set/s35_070115m.set_labeled_data.pkl
Deleted: /Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/preprocessed_data/s50_080731m.set/s50_080731m.set_l

In [7]:
import numpy as np

# Load the .npz file
data = np.load('/Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/Main_TF/labeled_datasets_811/s01_051017m.npz', allow_pickle=True)
keys = list(data.keys())

epoch_labels = data['epoch_labels']
features = data['features']

# Get the shape and basic statistics for epoch_labels
epoch_labels_shape = epoch_labels.shape
epoch_labels_unique, epoch_labels_counts = np.unique(epoch_labels, return_counts=True)
epoch_labels_info = dict(zip(epoch_labels_unique, epoch_labels_counts))

# Get the shape and basic statistics for features
features_shape = features.shape
features_min = features.min()
features_max = features.max()
features_mean = features.mean()
features_std = features.std()

print({
    "epoch_labels_shape": epoch_labels_shape,
    "features_shape": features_shape,
    "epoch_labels_info": epoch_labels_info,
    "features_min": features_min,
    "features_max": features_max,
    "features_mean": features_mean,
    "features_std": features_std
})


TypeError: unsupported operand type(s) for /: 'dict' and 'int'

In [6]:
import numpy as np

# Load the .npz file
data = np.load('Main_TF/labeled_datasets_811/s01_051017m.npz', allow_pickle=True)
features = data['features']

# Check the first sample of features
print(features)


{'delta': array([0.31995268, 0.39272907, 0.31546472, 0.29976391, 0.27651047,
       0.29548966, 0.54565131, 0.54029589, 0.51600783, 0.49805487,
       0.48411729, 0.47215947, 0.53253583, 0.45440484, 0.24057643,
       0.22777831, 0.25245867, 0.21831995, 0.23851973, 0.218955  ,
       0.22763558, 0.21163136, 0.21828038, 0.21803971, 0.23261841,
       0.22307435, 0.20923075, 0.20616415, 0.19398574, 0.21736501,
       0.18166132, 0.21360959, 0.21519179, 0.20791567, 0.1974934 ,
       0.1824877 , 0.19031786, 0.20938652, 0.21470789, 0.21632004,
       0.21733836, 0.25327502, 0.27820818, 0.27534574, 0.27518575,
       0.2591326 , 0.24598709, 0.20396692, 0.25029675, 0.26836281,
       0.27195018, 0.26967655, 0.25942422, 0.25373842, 0.29294518,
       0.24827836, 0.21089355, 0.28089214, 0.30880321, 0.34125015,
       0.32131197, 0.31337083, 0.31761784, 0.33219958, 0.33197355,
       0.32778115, 0.34189459, 0.33837081, 0.33244983, 0.34524533,
       0.28292807, 0.31685828, 0.22052436, 0.2229988

In [12]:
from mne_features.feature_extraction import extract_features
help(extract_features)

Help on function extract_features in module mne_features.feature_extraction:

extract_features(X, sfreq, selected_funcs, funcs_params=None, n_jobs=1, ch_names=None, return_as_df=False)
    Extraction of temporal or spectral features from epoched EEG signals.
    
    Parameters
    ----------
    X : ndarray, shape (n_epochs, n_channels, n_times)
        Array of epoched EEG data.
    
    sfreq : float
        Sampling rate of the data.
    
    selected_funcs : list of str or tuples
        The elements of ``selected_features`` are either strings or tuples of
        the form ``(str, callable)``. If an element is of type ``str``, it is
        the alias of a feature function. The aliases are built from the
        feature functions' names by removing ``compute_``. For instance, the
        alias of the feature function :func:`compute_ptp_amp` is ``ptp_amp``.
        (See the documentation of mne-features). If an element is of type
        ``tuple``, the first element of the tuple sho

In [2]:
directory_path = '/Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/Main_TF/labeled_datasets_811'

all_labels = []

# 1. Iterate over each file in the directory
for npz_file in [os.path.join(directory_path, f) for f in os.listdir(directory_path) if f.endswith('.npz')]:
    data = np.load(npz_file, allow_pickle=True)
    labels = data['epoch_labels']
    all_labels.extend(labels)

# 3. Calculate label distribution
label_distribution = {label: all_labels.count(label) for label in set(all_labels)}

print(label_distribution)


{0: 4244, 1: 5404}


Reading /Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/preprocessed_data/s09_060317n.set/s09_060317n.fdt
Reading 0 ... 1309279  =      0.000 ...  2618.558 secs...
Used Annotations descriptions: ['251', '252', '253', '254']
epoch_rt_list:
[8.992, 30.176, 33.064, 27.468, 31.628, 28.884, 28.756, 32.832, 27.7, 29.788, 29.572, 30.324, 33.952, 27.096, 32.132, 38.464, 19.912, 28.116, 69.36, 0.0, 38.58, 30.176, 35.64, 8.86, 35.504, 29.088, 26.864, 26.312, 69.796, 0.0, 20.744, 42.344, 55.62, 0.0, 51.656, 0.0, 39.616, 36.36, 13.976, 63.728, 0.0, 108.476, 0.0, 0.0, 8.624, 44.668, 99.468, 0.0, 0.0, 9.68, 25.776, 110.216, 0.0, 0.0, 13.608, 26.196, 30.156, 34.004, 29.404, 56.108, 0.0, 34.02, 25.928, 33.116, 35.34, 21.08, 35.256, 25.076, 30.408, 29.388, 30.376, 29.604, 30.96, 34.904, 25.376, 30.208, 28.536, 36.076, 24.708, 32.08, 27.7, 30.996, 29.588, 31.68, 27.6, 31.828,

In [2]:

import os
import mne
import numpy as np
import matplotlib.pyplot as plt
from mne_features.feature_extraction import extract_features

# Set the path to the folder containing the .set files
input_folder = '/Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/preprocessed_data'

# Set the path to the folder where the processed data will be saved
output_folder = '../labeled_data_811'

# Create the output folder if it does not exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Initialize a list to hold the labels of all epochs
all_labels = []

# Constants
EPOCH_LENGTH = 30
WINDOW_SIZE = 2
ALERT_RT_PERCENTILE = 5
ALERT_RT_MULTIPLIER = 1.3
FATIGUE_RT_MULTIPLIER = 1.8

def calculate_window_avg_rt(epoch_rt):
    # Calculate window average RT for each epoch: average of epoch RTs within the window
    return [np.mean(epoch_rt[max(0, i - WINDOW_SIZE): min(len(epoch_rt), i + WINDOW_SIZE)]) for i in range(len(epoch_rt))]

def calculate_labels(epoch_rt, window_avg_rt, alert_rt):
    # Label each epoch based on epoch RT and window average RT compared to alert RT
    return ['alert' if er < alert_rt * ALERT_RT_MULTIPLIER and wr < alert_rt * ALERT_RT_MULTIPLIER else
            'fatigued' for er, wr in zip(epoch_rt, window_avg_rt)]

# Iterate over the folders in the input folder
for foldername in os.listdir(input_folder):
    if foldername == '.DS_Store':
        continue
    # Get the .set file path
    filename = foldername
    filepath = os.path.join(input_folder, foldername, filename)

    # Load the data
    raw = mne.io.read_raw_eeglab(filepath, preload=True)

    # Set the epoch duration (in seconds)
    epoch_duration = 30

    # Calculate the number of epochs
    n_epochs = int(np.ceil(raw.times[-1] / epoch_duration))

    # Extract the events
    events = mne.events_from_annotations(raw)[0]

    # Calculate epoch RT for each epoch
    epoch_rt_list = []
    for i_epoch in range(n_epochs):
        # Indices of events that occur within this epoch
        epoch_event_indices = np.where((events[:, 0] >= i_epoch * EPOCH_LENGTH * raw.info['sfreq']) &
                                       (events[:, 0] < (i_epoch + 1) * EPOCH_LENGTH * raw.info['sfreq']))[0]

        # Ensure the indices do not go beyond the last event
        valid_indices = epoch_event_indices[epoch_event_indices < len(events) - 1]

        # Calculate epoch RT for this epoch
        epoch_rt = np.sum(events[valid_indices + 1, 0] - events[valid_indices, 0]) / raw.info['sfreq']
        epoch_rt_list.append(epoch_rt)

    # Calculate alert RT: the ALERT_RT_PERCENTILE percentile of all epoch RTs
    alert_rt = np.percentile(epoch_rt_list, ALERT_RT_PERCENTILE)

    # Calculate window average RT for each epoch
    window_avg_rt_list = calculate_window_avg_rt(epoch_rt_list)

    # Label each epoch
    labels = calculate_labels(epoch_rt_list, window_avg_rt_list, alert_rt)

    # Convert labels to numerical form for easier processing
    epoch_labels = [0 if label == 'alert' else 1 for label in labels]

    # Get the indices of the specified channels
    channels = ['FCZ', 'TP7', 'CP3', 'OZ']
    channel_indices = [raw.ch_names.index(ch) for ch in channels]

    # Initialize lists to hold the spectral and temporal data
    spectral_data = []
    temporal_data = []

    # Iterate over the epochs
    for i in range(n_epochs):
        # Extract the entire epoch data
        # start = i * epoch_duration
        # end = min((i + 1) * epoch_duration, raw.times[-1])
        start = max(i * epoch_duration, 0)
        end = min(i * epoch_duration + 3, raw.times[-1])
        epoch_data = raw.copy().crop(tmin=start, tmax=end).get_data()

        freqs = np.fft.rfftfreq(epoch_data.shape[1], 1 / raw.info['sfreq'])

        fft_vals = np.abs(np.fft.rfft(epoch_data, axis=1))
        delta_band = np.logical_and(freqs >= 0.5, freqs <= 4.5)
        theta_band = np.logical_and(freqs >= 4.5, freqs <= 8.5)
        alpha_band = np.logical_and(freqs >= 8.5, freqs <= 11.5)
        sigma_band = np.logical_and(freqs >= 11.5, freqs <= 15.5)
        beta_band = np.logical_and(freqs >= 15.5, freqs <= 30)
        delta_band = np.mean(fft_vals[:, delta_band], axis=-1)
        theta_data = np.mean(fft_vals[:, theta_band], axis=-1)
        alpha_data = np.mean(fft_vals[:, alpha_band], axis=-1)
        sigma_band = np.mean(fft_vals[:, sigma_band], axis=-1)
        beta_data = np.mean(fft_vals[:, beta_band], axis=-1)



        # Append the spectral data to the list
        spectral_data.append(np.stack([delta_band, theta_data, alpha_data, sigma_band, beta_data]))
        temp_data = epoch_data[channel_indices, :]
        # temporal_data.append(temp_data)

        # # Only append data of shape (4, 1501) to temporal_data
        if temp_data.shape == (4, 1501):
            temporal_data.append(temp_data)
        else:
            print(f"Skipping epoch {i} due to shape {temp_data.shape}")

        # Convert the lists to numpy arrays
    spectral_data = np.array(spectral_data)
    print(spectral_data)

Reading /Users/easonpeng/Desktop/University of Nottingham/Evaluation of Mental Fatigue at Multilevel using functional Near Infrared Spectroscopy/Evaluation-of-Mental-Fatigue-using-fNIRS/preprocessed_data/s09_060317n.set/s09_060317n.fdt
Reading 0 ... 1309279  =      0.000 ...  2618.558 secs...
Used Annotations descriptions: ['251', '252', '253', '254']
[[[0.00076438 0.00159467 0.00065871 ... 0.00089045 0.00089561 0.00086838]
  [0.00049163 0.00070412 0.00031205 ... 0.00054258 0.00054298 0.00063141]
  [0.00048028 0.00059273 0.00029643 ... 0.00056106 0.00056511 0.00067543]
  [0.00034343 0.00064019 0.0001793  ... 0.00037708 0.00038371 0.00048403]
  [0.00031172 0.00062882 0.00022129 ... 0.00023783 0.00024794 0.00032235]]

 [[0.00163239 0.00135903 0.00243323 ... 0.0010048  0.00100816 0.00116897]
  [0.00040636 0.00049978 0.00049338 ... 0.00041342 0.00043194 0.00042622]
  [0.0004778  0.00046119 0.00147204 ... 0.00043625 0.00043347 0.00039508]
  [0.00042941 0.00064025 0.00115014 ... 0.00036679 0

KeyboardInterrupt: 